<?php

function data_load_load_legacy_data() {
	$talks = module_load_include('inc', 'data_load', 'data_files/migrate.talks');
	load_talk_records();
	$khs = module_load_include('inc', 'data_load', 'data_files/migrate.kingdomHalls');
	load_kingdom_hall_records();
	$congs = module_load_include('inc', 'data_load', 'data_files/migrate.congregations');
	load_congregation_records();
	$times = module_load_include('inc', 'data_load', 'data_files/migrate.meeting_times');
	load_meeting_time_records();
	$talks = module_load_include('inc', 'data_load', 'data_files/migrate.brother');
	load_brother_records();
	$brother_talks = module_load_include('inc', 'data_load', 'data_files/migrate.brother_talk');
	load_brother_talk_records();
	$chairman = module_load_include('inc', 'data_load', 'data_files/migrate.chairman');
	load_chairman_records();
	$readers = module_load_include('inc', 'data_load', 'data_files/migrate.wt_reader');
	load_wt_reader_records();
}